// <auto-generated />
namespace IFSolutions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DateTimeToComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTimeToComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201502262251494_DateTimeToComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
